import { useEffect,useMemo,useState } from 'react';
import { api,ws } from '@appdeploy/client';
import { ShoppingCart,Search,Package,ShieldCheck,Phone,Mail,Truck,Plus,Minus,X,LogIn,Menu,ArrowRight,Printer } from 'lucide-react';

type Product={id:string;name:string;description:string;price:number;category:string;size:string;material:string};
type Order={id:string;order_id:string;tracking_id:string;customer:string;phone?:string;items:any[];total:number;status:string;payment_status:string;delivery_status:string;created_at:string;address?:string};
const PRODUCTS:Product[]=[
{id:'bc',name:'Business Cards',description:'Premium professional business cards with sharp finishing.',price:150,category:'Cards',size:'85×55mm',material:'300gsm Art Card'},
{id:'flyer',name:'Flyers',description:'High-quality promotional flyers for events and businesses.',price:100,category:'Marketing',size:'A5 / A4',material:'Art Paper'},
{id:'poster',name:'Posters',description:'Large-format posters with vibrant, durable prints.',price:500,category:'Marketing',size:'A3 / A2',material:'Gloss Art'},
{id:'banner',name:'Banners',description:'Bold outdoor and indoor banners for promotions.',price:2500,category:'Large Format',size:'Custom',material:'Flex'},
{id:'shirt',name:'T-Shirts',description:'Custom branded and event T-shirt printing.',price:3500,category:'Apparel',size:'S–XXL',material:'Cotton'},
{id:'booklet',name:'Booklets',description:'Clean, professional booklets for reports and presentations.',price:1200,category:'Books',size:'A5 / A4',material:'80gsm / Art'},
];
const STATUSES=['Order Received','Processing','Printing','Ready','Out for Delivery','Delivered'];
const money=(n:number)=>`₦${n.toLocaleString()}`;
function ProductCard({p,onAdd}:{p:Product;onAdd:()=>void}){return <div className="card hover:shadow-lg transition"><div className="h-36 rounded-2xl bg-gradient-to-br from-slate-100 to-blue-50 grid place-items-center text-5xl">🖨️</div><div className="mt-5"><span className="text-xs font-bold text-blue-700">{p.category}</span><h3 className="text-xl font-black mt-1">{p.name}</h3><p className="text-sm text-slate-500 mt-2 min-h-10">{p.description}</p><div className="mt-4 flex items-end justify-between"><div><span className="text-xs text-slate-400">Starting from</span><div className="font-black">{money(p.price)}</div></div><button className="btn-primary" onClick={onAdd}>Add <Plus size={15}/></button></div></div></div>}
function OrderCard({o}:{o:Order}){const idx=STATUSES.indexOf(o.status);return <div className="card mt-5 text-left"><div className="flex flex-wrap justify-between gap-3"><div><span className="text-xs text-slate-400">ORDER ID</span><div className="font-black">{o.order_id}</div><span className="text-xs text-slate-400">TRACKING</span><div className="font-mono text-sm">{o.tracking_id}</div></div><div className="text-right"><b>{money(o.total)}</b><div className="badge mt-1">{o.status}</div></div></div><div className="mt-6 grid grid-cols-6 gap-1">{STATUSES.map((s,i)=><div key={s} className="text-center"><div className={`h-2 rounded-full ${i<=idx?'bg-blue-600':'bg-slate-200'}`}/><span className="text-[9px] sm:text-xs text-slate-500">{s}</span></div>)}</div></div>}
function Stat({label,value}:{label:string;value:number}){return <div className="card"><div className="text-sm text-slate-500">{label}</div><div className="text-3xl font-black mt-1">{value}</div></div>}
function Admin({orders,onStatus,onRefresh}:{orders:Order[];onStatus:(o:Order,s:string)=>void;onRefresh:()=>void}){const[q,setQ]=useState('');const filtered=orders.filter(o=>(o.order_id+o.tracking_id+o.customer+(o.phone||'')).toLowerCase().includes(q.toLowerCase()));return <section className="mx-auto max-w-7xl px-4 py-10"><div className="flex flex-col md:flex-row justify-between gap-4"><div><span className="eyebrow">SECURE ADMIN</span><h2 className="title">Order Management</h2></div><button className="btn-secondary" onClick={onRefresh}>Refresh data</button></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-6"><Stat label="Total Orders" value={orders.length}/><Stat label="Pending" value={orders.filter(o=>o.status==='Order Received').length}/><Stat label="Processing" value={orders.filter(o=>o.status==='Processing'||o.status==='Printing').length}/><Stat label="Delivered" value={orders.filter(o=>o.status==='Delivered').length}/></div><div className="card mt-6"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-9" placeholder="Search ID, tracking or customer" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="overflow-x-auto mt-5"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500 border-b"><th className="p-3">Order</th><th className="p-3">Customer</th><th className="p-3">Total</th><th className="p-3">Status</th><th className="p-3">Control</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id} className="border-b last:border-0"><td className="p-3"><b>{o.order_id}</b><div className="font-mono text-xs text-slate-400">{o.tracking_id}</div></td><td className="p-3">{o.customer}<div className="text-xs text-slate-400">{o.phone}</div></td><td className="p-3 font-bold">{money(o.total)}</td><td className="p-3"><span className="badge">{o.status}</span></td><td className="p-3"><select className="input" value={o.status} onChange={e=>onStatus(o,e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table>{!filtered.length&&<p className="text-center py-10 text-slate-500">No matching orders.</p>}</div></div></section>}
export default function App(){const[page,setPage]=useState('home');const[cart,setCart]=useState<any[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[search,setSearch]=useState('');const[menu,setMenu]=useState(false);const[toast,setToast]=useState('');const[form,setForm]=useState({name:'',phone:'',email:'',password:'',address:''});const[login,setLogin]=useState({email:'',password:''});const[selected,setSelected]=useState<Product|null>(null);const[qty,setQty]=useState(1);const[tracking,setTracking]=useState('');
const subtotal=useMemo(()=>cart.reduce((s,i)=>s+i.price*i.qty,0),[cart]);const delivery=cart.length?500:0;const total=subtotal+delivery;
const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2500)};
const add=(p:Product,q=1)=>{setCart(c=>{const old=c.find(x=>x.id===p.id);return old?c.map(x=>x.id===p.id?{...x,qty:x.qty+q}:x):[...c,{...p,qty:q}]});notify(`${p.name} added to cart`)};
async function loadOrders(){try{const r=await api.get('/api/orders');setOrders(r.data.orders||[])}catch{}}
useEffect(()=>{loadOrders();const c=ws.connect();c.onMessage((m:any)=>{if(m?.type==='entity.update'){loadOrders();notify('Order data updated')}});return()=>c.disconnect()},[]);
async function createOrder(){if(!cart.length)return;if(!form.name||!form.phone){notify('Name and phone are required');return}try{const r=await api.post('/api/orders',{customer:form.name,phone:form.phone,email:form.email,items:cart,total,delivery_fee:delivery,address:form.address});const o=r.data.order;setOrders(x=>[o,...x]);setCart([]);setPage('orders');notify(`Order ${o.order_id} created`)}catch{notify('Could not create order. Please try again.')}}
async function updateStatus(o:Order,status:string){try{await api.put(`/api/orders/${o.id}`,{status});setOrders(xs=>xs.map(x=>x.id===o.id?{...x,status}:x));notify('Order status updated')}catch{notify('Update failed')}}
const filtered=PRODUCTS.filter(p=>(p.name+p.description+p.category).toLowerCase().includes(search.toLowerCase()));
return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="bg-slate-950 text-white text-xs"><div className="mx-auto max-w-7xl px-4 py-2 flex justify-between gap-4"><span>Quality Printing. Professional Results.</span><span className="flex gap-4"><a href="mailto:favoursamuel3098@gmail.com">favoursamuel3098@gmail.com</a><a href="tel:09054434502">09054434502</a></span></div></div><div className="mx-auto max-w-7xl px-4 h-16 flex items-center justify-between"><button onClick={()=>setPage('home')} className="flex items-center gap-2 font-black text-lg"><span className="rounded-xl bg-slate-950 text-white p-2"><Printer size={20}/></span> FRANK ALEX <span className="hidden sm:inline text-blue-700">PRINTING PRESS</span></button><nav className={`${menu?'flex':'hidden'} md:flex absolute md:static top-full left-0 right-0 bg-white md:bg-transparent p-4 md:p-0 flex-col md:flex-row gap-3 shadow md:shadow-none`}><button onClick={()=>setPage('services')} className="nav">Services</button><button onClick={()=>setPage('track')} className="nav">Track Order</button><button onClick={()=>setPage('orders')} className="nav">My Orders</button><button onClick={()=>setPage('admin')} className="nav"><ShieldCheck size={15}/> Admin</button></nav><div className="flex items-center gap-2"><button className="relative rounded-xl border p-2" onClick={()=>setPage('cart')}><ShoppingCart size={19}/>{cart.length>0&&<b className="absolute -right-2 -top-2 rounded-full bg-blue-600 text-white text-[10px] px-1.5">{cart.length}</b>}</button><button className="md:hidden p-2" onClick={()=>setMenu(!menu)}><Menu/></button><button onClick={()=>setPage('login')} className="hidden sm:flex btn-secondary"><LogIn size={16}/>Login</button></div></div></header>{toast&&<div className="fixed right-4 top-24 z-50 rounded-xl bg-slate-950 text-white px-4 py-3 shadow-xl text-sm">{toast}</div>}<main>
{page==='home'&&<><section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-20 md:py-28 grid md:grid-cols-2 gap-10 items-center"><div><span className="badge">PROFESSIONAL PRINTING</span><h1 className="mt-5 text-4xl md:text-6xl font-black leading-tight">Print it. Brand it. <span className="text-blue-400">Make it stand out.</span></h1><p className="mt-5 text-slate-300 text-lg max-w-xl">From business cards and flyers to banners, T-shirts and booklets, Frank Alex Printing Press delivers quality printing with professional results.</p><div className="mt-8 flex flex-wrap gap-3"><button className="btn-primary" onClick={()=>setPage('services')}>Browse Services <ArrowRight size={17}/></button><button className="btn-light" onClick={()=>setPage('cart')}>Order Now</button></div></div><div className="rounded-3xl border border-white/10 bg-white/5 p-8"><div className="grid grid-cols-2 gap-4">{PRODUCTS.slice(0,4).map(p=><div key={p.id} className="rounded-2xl bg-white/10 p-5"><div className="text-3xl">🖨️</div><div className="mt-4 font-bold">{p.name}</div><div className="text-sm text-slate-400">From {money(p.price)}</div></div>)}</div></div></div></section><section className="mx-auto max-w-7xl px-4 py-16"><div className="flex justify-between items-end mb-8"><div><span className="eyebrow">OUR SERVICES</span><h2 className="title">Popular printing services</h2></div><button onClick={()=>setPage('services')} className="text-blue-700 font-bold">View all →</button></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{PRODUCTS.map(p=><ProductCard key={p.id} p={p} onAdd={()=>{setSelected(p);setQty(1)}}/>)}</div></section></>}
{page==='services'&&<section className="mx-auto max-w-7xl px-4 py-12"><div className="flex flex-col md:flex-row md:items-end justify-between gap-5 mb-8"><div><span className="eyebrow">CATALOG</span><h2 className="title">Choose what you want printed</h2></div><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="input pl-10" placeholder="Search services..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{filtered.map(p=><ProductCard key={p.id} p={p} onAdd={()=>{setSelected(p);setQty(1)}}/>)}</div></section>}
{page==='cart'&&<section className="mx-auto max-w-5xl px-4 py-12"><h2 className="title">Shopping Cart</h2>{!cart.length?<div className="card mt-6 text-center py-16"><ShoppingCart className="mx-auto mb-4 text-slate-300" size={48}/><p>Your cart is empty.</p><button className="btn-primary mt-5" onClick={()=>setPage('services')}>Browse Services</button></div>:<div className="mt-6 grid lg:grid-cols-[1fr_340px] gap-6"><div className="space-y-3">{cart.map(i=><div className="card flex items-center gap-4" key={i.id}><div className="h-16 w-16 rounded-xl bg-slate-100 grid place-items-center text-2xl">🖨️</div><div className="flex-1"><b>{i.name}</b><p className="text-sm text-slate-500">{money(i.price)} each</p></div><div className="flex items-center gap-2"><button className="icon" onClick={()=>setCart(c=>c.map(x=>x.id===i.id?{...x,qty:Math.max(1,x.qty-1)}:x))}><Minus size={15}/></button><span>{i.qty}</span><button className="icon" onClick={()=>setCart(c=>c.map(x=>x.id===i.id?{...x,qty:x.qty+1}:x))}><Plus size={15}/></button></div><b>{money(i.price*i.qty)}</b><button onClick={()=>setCart(c=>c.filter(x=>x.id!==i.id))}><X size={18}/></button></div>)}</div><div className="card h-fit"><h3 className="font-bold text-lg">Checkout summary</h3><div className="summary"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="summary"><span>Delivery</span><b>{money(delivery)}</b></div><div className="summary total"><span>Total</span><b>{money(total)}</b></div><input className="input" placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input mt-3" placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><textarea className="input mt-3" placeholder="Delivery address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><button className="btn-primary w-full mt-4" onClick={createOrder}>Place Order</button></div></div>}</section>}
{page==='orders'&&<section className="mx-auto max-w-6xl px-4 py-12"><div className="flex justify-between"><div><span className="eyebrow">CUSTOMER PORTAL</span><h2 className="title">My Orders</h2></div><button className="btn-secondary" onClick={loadOrders}><Package size={16}/> Refresh</button></div><div className="mt-6 space-y-4">{orders.length?orders.map(o=><OrderCard key={o.id} o={o}/>):<div className="card py-14 text-center text-slate-500">No orders yet. <button className="text-blue-700 font-bold" onClick={()=>setPage('services')}>Start an order</button></div>}</div></section>}
{page==='track'&&<section className="mx-auto max-w-3xl px-4 py-16"><div className="card text-center"><Truck className="mx-auto text-blue-600" size={42}/><h2 className="title mt-4">Track your order</h2><p className="text-slate-500 mt-2">Enter your tracking ID to see the latest status.</p><div className="flex gap-2 mt-6"><input className="input" placeholder="FAP-X82K7M9Q" value={tracking} onChange={e=>setTracking(e.target.value)}/><button className="btn-primary" onClick={()=>{const o=orders.find(x=>x.tracking_id===tracking);notify(o?o.status:'Tracking ID not found')}}>Track</button></div>{orders.filter(o=>o.tracking_id===tracking).map(o=><OrderCard key={o.id} o={o}/>)}</div></section>}
{page==='login'&&<section className="mx-auto max-w-md px-4 py-16"><div className="card"><span className="eyebrow">CUSTOMER ACCOUNT</span><h2 className="title text-3xl mt-2">Welcome back</h2><input className="input mt-6" placeholder="Email or phone" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input className="input mt-3" type="password" placeholder="Password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button className="btn-primary w-full mt-5" onClick={()=>{notify('Login submitted');setPage('orders')}}>Login</button><button className="w-full mt-4 text-blue-700 font-bold" onClick={()=>setPage('register')}>Create an account</button></div></section>}
{page==='register'&&<section className="mx-auto max-w-lg px-4 py-12"><div className="card"><span className="eyebrow">CREATE ACCOUNT</span><h2 className="title text-3xl mt-2">Register</h2><div className="grid sm:grid-cols-2 gap-3 mt-6">{[['name','Full Name'],['phone','Phone'],['email','Email'],['password','Password'],['address','Delivery Address']].map(([k,l])=><input key={k} className="input" type={k==='password'?'password':'text'} placeholder={l} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}</div><button className="btn-primary w-full mt-5" onClick={()=>{notify('Account registration submitted');setPage('orders')}}>Register</button></div></section>}
{page==='admin'&&<Admin orders={orders} onStatus={updateStatus} onRefresh={loadOrders}/>}</main>{selected&&<div className="fixed inset-0 z-50 bg-black/50 grid place-items-center p-4"><div className="card max-w-md w-full"><div className="flex justify-between"><div><span className="eyebrow">CUSTOM ORDER</span><h3 className="text-2xl font-black mt-1">{selected.name}</h3></div><button onClick={()=>setSelected(null)}><X/></button></div><p className="text-slate-500 mt-3">{selected.description}</p><div className="mt-5 grid grid-cols-2 gap-3"><label className="label">Quantity<input className="input mt-1" type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,+e.target.value))}/></label><label className="label">Size<input className="input mt-1" value={selected.size} readOnly/></label><label className="label">Material<input className="input mt-1" value={selected.material} readOnly/></label><label className="label">Finishing<select className="input mt-1"><option>Standard</option><option>Gloss</option><option>Matte</option></select></label></div><p className="mt-5 font-bold">Starting price: {money(selected.price)} × {qty}</p><button className="btn-primary w-full mt-4" onClick={()=>{add(selected,qty);setSelected(null);setPage('cart')}}>Add to Cart</button></div></div>}<footer className="bg-slate-950 text-slate-300 mt-16"><div className="mx-auto max-w-7xl px-4 py-10 grid md:grid-cols-3 gap-8"><div><div className="text-white font-black text-lg">FRANK ALEX PRINTING PRESS</div><p className="mt-2 text-sm">Quality Printing. Professional Results.</p></div><div><b className="text-white">Contact</b><p className="mt-2 flex gap-2"><Mail size={16}/> favoursamuel3098@gmail.com</p><p className="mt-2 flex gap-2"><Phone size={16}/> 09054434502</p></div><div><b className="text-white">Quick actions</b><div className="mt-2 flex gap-4 text-sm"><button onClick={()=>setPage('services')}>Services</button><button onClick={()=>setPage('track')}>Track</button><button onClick={()=>setPage('admin')}>Admin</button></div></div></div><div className="border-t border-white/10 text-center text-xs py-4">© 2026 Frank Alex Printing Press. All rights reserved.</div></footer></div>}
